Src=ConvectionDrive2d.c \
	Convection2d.h \
	ConvectionRHS2d.c \
	ConvectionSolve2d.c \
	../Utilities/utils.c \
	../Utilities/utils.h \

Convection2d:
	icc ${Src} -o $@

clean:
	rm *.txt
	rm Convection2d
